language: android
env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
  ./gradlew build
